gantt
    title Roadmap geo-standaarden
    dateFormat YYYY-M
    axisFormat Q%q %Y
    tickInterval 3month
    section ONT
        %% Consultatie GeoPackage and Spatial Schema   :done,      2023-07, 3M
        % Update PTOLU Geo-standaarden                :done,    2023-10, 6M
        %% PoC Rechtendelegatie (oAuth)                :           2023-10, 3M
        %% OGC Code Sprint                             :           2023-10, 1M        
        %%Consultatie IMX-Geo                         :           2024-01, 3M
        Update Handreiking CRS                      :           2024-01, 6M        
        Handreiking 3D Tiles                        :active,          2024-02, 6M
        Handreiking Geopackage                      :           2024-07, 6M
        
    section DM        
        %%IMEV 2.0                                    :done,    2023-10, 3M
        %%IMG                                         :done,    2023-10, 3M
        IMGeo - Voorstel basisobjecten en sectordata:active,    2024-01, 7M
        IMGeo - Update pastelvisualisatie                :      2024-09, 3M
        IMOW                                        :           2024-01, 12M
        IMEV                                        :           2024-01, 12M
        %% IMKL                                        :           2023-09, 
        %% IMKAD                                       :           2023-09, 
        %% IMWOZ                                       :           2023-09, 
        %% IMBAG                                       :           2023-09, 
        %% IMBOR                                       :           2023-09, 
        %% GWSW                                        :           2023-09, 
        %% IMNA                                        :           2023-09, 
        %% IMDBK / IMROI                               :           2023-09, 
        %% BRT.Next                                    :           2023-09, 

    section TS
        %%GeoPackage 1.4                              :active,    2023-10, 3M
        %%CityJSON 2.0                                :active,    2023-10, 3M
        %%OGC Training DML-AI 1.0                     :active,    2023-10, 3M
        %%Consultatie standaard voor begrippenkaders  :           2023-10, 3M        
        Standaard voor begrippenkaders SBB v1.0.0       :           2024-01, 3M
        DCAT 3.0                                    :           2024-03, 3M 
        ISO JSON encoding 19115                     :           2024-01, 12M
        API strategie module filtering              :           2024-01, 12M
        OGC API Records                             :           2024-01, 12M
        OGC API Features part 3                     :           2024-01, 12M
        JSON-FG consultatie                         :           2024-01, 12M
        DCAT NL-profiel 1.0                         :           2024-01, 12M
        Update NL API-strategie (NL REST API Design rules) :    2024-01, 12M
        MIM?                                               :    2023-09,
